In [52]:
import pandas as pd
df=pd.read_csv("raw_data.csv")
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [45]:
df2=df.copy()
df2=df2.drop_duplicates()
df2["gender"]=df2["gender"].fillna("Female")
df2=df2.fillna(0)

df2=df2.sort_values("income")
df2=df2.reset_index(drop=True)
df2.to_csv("sorted_data.csv")

In [46]:
#Groupby , mean/max/sum/min/count , agg()

In [47]:
df2.groupby("country")["income"].mean()

country
0         68000.0
Canada    62000.0
China     51000.0
India     73000.0
Mexico    45000.0
Spain         0.0
USA       55500.0
Name: income, dtype: float64

In [48]:
df2.groupby("country")["income"].min()

country
0         68000.0
Canada    62000.0
China     51000.0
India     73000.0
Mexico    45000.0
Spain         0.0
USA       47000.0
Name: income, dtype: float64

In [49]:
df2.groupby("country")["income"].max()

country
0         68000.0
Canada    62000.0
China     51000.0
India     73000.0
Mexico    45000.0
Spain         0.0
USA       62000.0
Name: income, dtype: float64

In [53]:
df2.groupby("gender")["income"].max()

gender
Female     73000.0
Male       68000.0
Unknown    47000.0
Name: income, dtype: float64

In [55]:
df2.groupby("gender")["income"].agg(["mean","max","min"])

            mean      max      min
gender
Female   51000.0  73000.0      0.0
Male     54750.0  68000.0  45000.0
Unknown  47000.0  47000.0  47000.0

In [ ]:
df2.groupby("gender")["income"].aggregate(["mean","max","min"])

In [58]:
df2.groupby("gender")["income"].agg(avg_salary="mean",max_salary="max",min_salary="min")

         avg_salary  max_salary  min_salary
gender
Female      51000.0     73000.0         0.0
Male        54750.0     68000.0     45000.0
Unknown     47000.0     47000.0     47000.0

In [63]:
df.groupby("country").agg({
    "income":"max",
    "age" :"mean"
})

          income   age
country
Canada   62000.0   NaN
China    51000.0  27.0
India    73000.0  45.0
Mexico   45000.0   NaN
Spain        NaN  34.0
USA      62000.0  29.5

In [67]:
df.groupby("country").agg(
    max_salary=("income","max"),
    avg_age=("age","mean")
)

         max_salary  avg_age
country
Canada      62000.0      NaN
China       51000.0     27.0
India       73000.0     45.0
Mexico      45000.0      NaN
Spain           NaN     34.0
USA         62000.0     29.5