In [ ]:
#Merging And Joining Data

In [2]:
# Merging & Joining Data

import pandas as pd

df_customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "name": ["Adam", "Bob", "Charlie", "Dave"]
})

df_orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104],
    "customer_id": [2, 1, 4, 5],
    "amount": [250, 120, 300, 180]
})

In [2]:
df_customers

   customer_id     name
0            1     Adam
1            2      Bob
2            3  Charlie
3            4     Dave

In [3]:
df_orders

   order_id  customer_id  amount
0       101            2     250
1       102            1     120
2       103            4     300
3       104            5     180

In [5]:
pd.merge(df_customers,df_orders,on="customer_id")

   customer_id  name  order_id  amount
0            1  Adam       102     120
1            2   Bob       101     250
2            4  Dave       103     300

In [7]:
pd.merge(df_customers,df_orders,on="customer_id" , how="left")

   customer_id     name  order_id  amount
0            1     Adam     102.0   120.0
1            2      Bob     101.0   250.0
2            3  Charlie       NaN     NaN
3            4     Dave     103.0   300.0

In [6]:
pd.merge(df_customers,df_orders,on="customer_id" , how="right")

   customer_id  name  order_id  amount
0            2   Bob       101     250
1            1  Adam       102     120
2            4  Dave       103     300
3            5   NaN       104     180

In [8]:
pd.merge(df_customers,df_orders,on="customer_id" , how="outer")

   customer_id     name  order_id  amount
0            1     Adam     102.0   120.0
1            2      Bob     101.0   250.0
2            3  Charlie       NaN     NaN
3            4     Dave     103.0   300.0
4            5      NaN     104.0   180.0

In [ ]:
# Data Concetation :-  Stacking DataFrames on top of each other (rows) or side  by side (columns)

In [3]:
df1 = pd.DataFrame({
    "id": [1, 2, 3],
    "name": ["Adam", "Eve", "Bob"]
})

df2 = pd.DataFrame({
    "id": [4, 5, 6],
    "name": ["Charlie", "Fester", "Gilian"]
})

In [4]:
df1

   id  name
0   1  Adam
1   2   Eve
2   3   Bob

In [5]:
df2

   id     name
0   4  Charlie
1   5   Fester
2   6   Gilian

In [6]:
pd.concat([df1,df2]) # row

   id     name
0   1     Adam
1   2      Eve
2   3      Bob
0   4  Charlie
1   5   Fester
2   6   Gilian

In [7]:
pd.concat([df1,df2] , axis = 1) # col

   id  name  id     name
0   1  Adam   4  Charlie
1   2   Eve   5   Fester
2   3   Bob   6   Gilian

In [10]:
pd.concat([df1,df2] , axis = 1 ,ignore_index=True) # col

   0     1  2        3
0  1  Adam  4  Charlie
1  2   Eve  5   Fester
2  3   Bob  6   Gilian

In [11]:
pd.concat([df1,df2] , ignore_index=True) #row

   id     name
0   1     Adam
1   2      Eve
2   3      Bob
3   4  Charlie
4   5   Fester
5   6   Gilian